### ISSUE TITLE
前端只配置 dashboard会报错

### ISSUE THREAD

**Issue by jundaychan** [openscrm/dashboard#7]
react-dom.production.min.js:141 TypeError: Cannot read properties of null (reading 'children')
    at vendors~layouts__BasicLayout~layouts__LoginLayout.5d573adf.async.js:4:5582
    at Array.map (<anonymous>)
    at e (vendors~layouts__BasicLayout~layouts__LoginLayout.5d573adf.async.js:4:5558)
    at vendors~layouts__BasicLayout~layouts__LoginLayout.5d573adf.async.js:4:5613
    at Array.map (<anonymous>)
    at e (vendors~layouts__BasicLayout~layouts__LoginLayout.5d573adf.async.js:4:5558)
    at Ve (vendors~layouts__BasicLayout~layouts__LoginLayout.5d573adf.async.js:4:5817)
    at b (vendors~layouts__BasicLayout~layouts__LoginLayout.5d573adf.async.js:4:7945)
    at b (vendors~layouts__BasicLayout~layouts__LoginLayout.5d573adf.async.js:4:8021)
    at layouts__BasicLayout.5bd08d2f.async.js:1:54872

报错信息

**Comment by leeless** [comment]
同遇到这个问题，你解决了吗

**Comment by kernelpod** [comment]
可以去Goframe官网，告知管理，这都是弃用的没人维护的废项目，从官网移除吧
